www/stock/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url
# from django.conf import settings

urlpatterns = patterns('www.stock.views',
                       url(r'^$', 'stock_home'),
                       url(r'^my_stock_feeds$', 'my_stock_feeds'),
                       url(r'^all$', 'stock_all'),
                       url(r'^(?P<stock_code>\d+)$', 'stock_detail'),
                       url(r'^feed/(?P<stock_feed_id>\d+)$', 'stock_feed'),
                       url(r'^search$', 'stock_search'),
                       url(r'^my_stocks$', 'my_stocks'),

                       url(r'^follow/(?P<stock_id>\d+)$', 'follow_stock'),
                       url(r'^unfollow/(?P<stock_id>\d+)$', 'unfollow_stock'),
                       url(r'^get_stock_info_by_id$', 'get_stock_info_by_id'),

                       url(r'^chart_stock$', 'chart_stock'),
                       url(r'^chart_kind$', 'chart_kind'),
                       url(r'^chart_kind/(?P<kind_id>\d+)$', 'chart_kind_detail'),

                       # 个股前十
                       url(r'^get_stock_chain_data$', 'get_stock_chain_data'),
                       url(r'^get_stock_percent_in_total_data$', 'get_stock_percent_in_total_data'),

                       # 个股历史
                       url(r'^get_stock_k_line_data$', 'get_stock_k_line_data'),
                       url(r'^get_stock_history_chain_data$', 'get_stock_history_chain_data'),
                       url(r'^get_stock_history_percent_in_total_data$', 'get_stock_history_percent_in_total_data'),
                       
                       # 行业
                       url(r'^get_kind_chain_data$', 'get_kind_chain_data'),
                       url(r'^get_kind_percent_in_total_data$', 'get_kind_percent_in_total_data'),

                       url(r'^get_kind_history_chain_data$', 'get_kind_history_chain_data'),
                       url(r'^get_kind_history_percent_in_total_data$', 'get_kind_history_percent_in_total_data'),
                       url(r'^get_stock_chain_data_of_kind$', 'get_stock_chain_data_of_kind'),
                       url(r'^get_stock_percent_in_total_data_of_kind$', 'get_stock_percent_in_total_data_of_kind'),

                       url(r'^get_stock_json$', 'get_stock_json'),
                       url(r'^sync_stock_data$', 'sync_stock_data'),
                       )

www/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', 'www.misc.views.show_index_for_all_domain'),
                       url(r'^home$', 'www.account.views.show_index'),
                       url(r'^login$', 'www.account.views.login'),
                       url(r'^logout$', 'www.account.views.logout'),
                       url(r'^regist$', 'www.account.views.regist'),
                       url(r'^regist/(?P<invitation_code>\w+)$', 'www.account.views.regist'),
                       url(r'^reset_password$', 'www.account.views.reset_password'),
                       url(r'^forget_password$', 'www.account.views.forget_password'),
                       url(r'^qiniu_img_return$', 'www.misc.views.qiniu_img_return'),
                       url(r'^save_img$', 'www.misc.views.save_img'),
                       url(r'^crop_img$', 'www.misc.views.crop_img'),
                       url(r'^search_auto_complete$', 'www.question.views.search_auto_complete'),
                       url(r'^search$', 'www.question.views.search'),

                       url(r'^n/(?P<nick>.*)$', 'www.account.views.get_user_by_nick'),
                       url(r'^p/(?P<user_id>\w+)/?$', 'www.account.views.user_questions'),
                       url(r'^p/(?P<user_id>\w+)/questions/?$', 'www.account.views.user_questions'),
                       url(r'^p/(?P<user_id>\w+)/answers/?$', 'www.account.views.user_answers'),
                       url(r'^p/(?P<user_id>\w+)/following/?$', 'www.account.views.user_following'),
                       url(r'^p/(?P<user_id>\w+)/followers/?$', 'www.account.views.user_followers'),

                       url(r'^account/', include('www.account.urls')),
                       url(r'^question/', include('www.question.urls')),
                       url(r'^message/', include('www.message.urls')),
                       url(r'^timeline/', include('www.timeline.urls')),
                       url(r'^weixin/', include('www.weixin.urls')),
                       url(r'^zt/', include('www.zhuanti.urls')),
                       url(r'^kaihu/', include('www.kaihu.urls')),
                       url(r'^admin/', include('www.admin.urls')),
                       url(r'^stock/', include('www.stock.urls')),
                       url(r'^toutiao/', include('www.toutiao.urls')),

                       url(r'^auth_custom_manager$', 'www.kaihu.views.auth_custom_manager'),
                       url(r'^get_departments_by_name$', 'www.kaihu.views.get_departments_by_name'),
                       url(r'^baidu_map$', 'www.misc.views.baidu_map'),
                       url(r'^baidu_map.html$', 'www.misc.views.baidu_map'),
                       url(r'^sitemap.xml$', 'www.misc.views.sitemap'),
                       # url(r'^8efc199540223825b0fb2026cc9b8e39\.html$', 'www.misc.views.link_view'),
                       url(r'^(?P<txt_file_name>\w+)\.txt$', 'www.misc.views.txt_view'),
                       url(r'^s/links$', 'www.misc.views.friendly_links'),
                       url(r'^s/(?P<template_name>.*)$', 'www.misc.views.static_view'),
                       url(r'^500$', 'www.account.views.test500'),
                       url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': False}),
                       )

# 冗余url，用于减少url层级
urlpatterns += patterns('',
                        url(r'^topic/(?P<topic_domain>\w+)$', 'www.question.views.topic_question'),
                        url(r'^topics$', 'www.question.views.topics'),
                        url(r'^important/?$', 'www.question.views.important_question'),
                        )

www/stock/models.py
# -*- coding: utf-8 -*-

from django.db import models


class Stock(models.Model):
    board_choices = ((0, u'主板'), (1, u"中小企业板"), (2, u"创业板"), (3, u"B股"), (4, u"其他"))
    market_choices = ((0, u'沪股市'), (1, u"深圳股市"))

    name = models.CharField(max_length=64, unique=True)
    origin_uid = models.CharField(max_length=16, unique=True)
    code = models.CharField(max_length=16, unique=True)
    des = models.TextField(null=True)
    main_business = models.TextField(null=True)  # 主营业务
    belong_board = models.IntegerField(choices=board_choices)   # 所属板块
    belong_market = models.IntegerField(choices=market_choices)   # 所属交易所

    img = models.CharField(max_length=128)
    feed_count = models.IntegerField(default=0, db_index=True)
    following_count = models.IntegerField(default=0, db_index=True)
    sort_num = models.IntegerField(default=0, db_index=True)
    state = models.BooleanField(default=True, db_index=True)
    create_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-sort_num", '-feed_count']

    def get_url(self):
        return u'/stock/%s' % self.code


class StockFeed(models.Model):
    market_choices = ((0, u'沪股市'), (1, u"深圳股市"))

    stock = models.ForeignKey(Stock)
    question_content = models.CharField(max_length=1024)
    answer_content = models.TextField()
    origin_id = models.CharField(max_length=16, unique=True, null=True)  # 对象的id
    belong_market = models.IntegerField(choices=market_choices)   # 所属交易所

    state = models.BooleanField(default=True, db_index=True)
    create_question_time = models.DateTimeField(db_index=True, null=True)
    create_time = models.DateTimeField(db_index=True)

    class Meta:
        ordering = ["-create_time", "id"]

    def get_url(self):
        return u'/stock/feed/%s' % self.id


class StockFollow(models.Model):
    source_choices = ((0, u'站内直接关注'), (1, u''))

    user_id = models.CharField(max_length=32, db_index=True)
    stock = models.ForeignKey(Stock)
    source = models.IntegerField(default=0, choices=source_choices)
    create_time = models.DateTimeField(db_index=True, auto_now_add=True)

    class Meta:
        unique_together = ("user_id", "stock")
        ordering = ['-id']


class StockData(models.Model):
    stock = models.ForeignKey("Stock")
    date = models.DateField(db_index=True)
    market_value = models.FloatField(default=0)
    open_price = models.FloatField()
    close_price = models.FloatField()
    low_price = models.FloatField()
    high_price = models.FloatField()
    volume = models.FloatField(db_index=True)  # 成交手数量
    turnover = models.FloatField(db_index=True)  # 成交金额
    turnover_rate_to_all = models.FloatField(db_index=True, default=0)  # 占总交易额的百分比
    turnover_rate_to_all_change_per_day = models.FloatField(db_index=True, default=0)  # 占总比的变化
    turnover_change_pre_day = models.FloatField(db_index=True, default=0)  # 相对于前一天的变化的百分比

    class Meta:
        unique_together = ("stock", "date")
        ordering = ['-date', '-id']

    def __unicode__(self):
        return "%s:%s" % (self.id, self.date)


class Kind(models.Model):

    """
    @note: 行业分类
    """
    group_choices = ((0, u"行业"), (1, u"概念"), (99, u"自定义"))

    name = models.CharField(max_length=64, unique=True)
    group = models.IntegerField(db_index=True, default=0, choices=group_choices)
    sort_num = models.IntegerField(default=0, db_index=True)
    state = models.BooleanField(default=True, db_index=True)


class StockKind(models.Model):

    """
    @note: 股票对应的行业
    """
    stock = models.ForeignKey("Stock", related_name="stock_kind")
    kind = models.ForeignKey("Kind", related_name="stocks")


class KindData(models.Model):
    kind = models.ForeignKey("Kind")
    date = models.DateField(db_index=True)
    turnover = models.FloatField(db_index=True)  # 成交金额
    turnover_rate_to_all = models.FloatField(db_index=True, default=0)  # 占总交易额的百分比
    turnover_rate_to_all_change_per_day = models.FloatField(db_index=True, default=0)  # 占总比的变化
    turnover_change_pre_day = models.FloatField(db_index=True, default=0)  # 相对于前一天的变化的百分比

    class Meta:
        unique_together = ("kind", "date")
        ordering = ['-date', '-id']

www/templates/stock/_hot_stock.html
<div class="pb-5 mt-10 pt-10 top-border bdc-eee pt-5">
    <span class="f16 fb">热门股票</span>
    <a href="/stock/all" class="f12 co8 pull-right more-topics">更多股票 »</a>
</div>
<ul class="list-group">
    {% for stock in stocks %}
    <li class="list-group-item no-l-r-bd bdc-eee pl-0">
        <a href="{{stock.get_url}}"><img class="pa avatar-45 avatar-square" src="{{stock.img}}" alt="{{stock.name}}"></a>
        <div class="pl-55">
            <div class="f14 pt-5"><a class="zx-stocktips" data-stock_id="{{stock.id}}" href="{{stock.get_url}}">{{stock.name}}({{stock.code}})</a></div>
            <div class="f12 co8 pt-3">{{stock.feed_count}} 条动态 <span class="pl-3 pr-3">•</span> {{stock.following_count}} 人关注</div>
        </div>
    </li>
    {% endfor %}
</ul>

www/templates/stock/_my_stock.html
{% if request.user.is_authenticated %}
<div class="pb-5 mt-10 pt-10 top-border bdc-eee pt-5">
    <span class="f16 fb">我关注的股票</span>
    <a href="/stock/my_stocks" class="f12 co8 pull-right more-topics">更多关注 »</a>
</div>
{% if stocks %}
<ul class="list-group">
    {% for stock in stocks %}
    <li class="list-group-item no-l-r-bd bdc-eee pl-0">
        <a href="{{stock.get_url}}"><img class="pa avatar-45 avatar-square" src="{{stock.img}}" alt="{{stock.name}}"></a>
        <div class="pl-55">
            <div class="f14 pt-5"><a class="zx-stocktips" data-stock_id="{{stock.id}}" href="{{stock.get_url}}">{{stock.name}}({{stock.code}})</a></div>
            <div class="f12 co8 pt-3">{{stock.feed_count}} 条动态 <span class="pl-3 pr-3">•</span> {{stock.following_count}} 人关注</div>
        </div>
    </li>
    {% endfor %}
</ul>
{% else %}
<div class="alert alert-info popmsg box-shadow-224 border-radius-0">暂未关注股票</div>
{% endif %}
{% endif %}

www/templates/stock/base_stock.html
{% extends "base/base_home.html" %}
{% load custom_tags %}
{% load custom_filters %}

{% block home_css %}
{% block css %}{% endblock %}
{% endblock %}

{% block home_js%}
{% block javascript %}{% endblock %}
{% endblock %}

{% block container_content %}
<div class="col-xs-12 col-md-8 ">
    {% block stock_main%}{% endblock %}
</div>

<div class="col-xs-12 col-md-4 pl-50">
	{% block stock_right_search %}
    <div class="pb-5">
        <form action="/stock/search" class="pt-15 pb-5">
            <input type="text" class="form-control input-sm pr-30" name="key_words" placeholder="输入上市公司名称 / 代码" value="{{stock_key_words}}" maxlength="50">
            <button type="submit" class="pa f16 pointer no-border bgc-0" style="right: 15px; top: 22px;"><span class="fa fa-search co8" ></span></button>
        </form>
    </div>
    {% endblock %}

    {% block stock_right %}

    {% my_stock %}
    {% hot_stock %}

    <!-- 百度站内搜索 
    <script type="text/javascript">document.write(unescape('%3Cdiv id="bdcs"%3E%3C/div%3E%3Cscript charset="utf-8" src="http://rp.baidu.com/rp3w/3w.js?sid=6625555038042837712') + '&t=' + (Math.ceil(new Date()/3600000)) + unescape('"%3E%3C/script%3E'));</script>
    -->
    {% endblock %}
</div>
{% endblock container_content %}

www/templates/stock/stock_all.html
{% extends "stock/base_stock.html" %}
{% load custom_tags %}
{% load custom_filters %}
{% block keywords %}股票一览表,A股,B股,主板,中小板,创业板{% endblock keywords %}

{% block description %}股票一览表包含：主板，中小板，创业板等上市公司股票简称及股票代码，点击可查看上市公司最新动态、个股最新问答、最新公告、公司新闻等信息。{% endblock description %}

{% block title %}股票一览表{% endblock title %}

{% block javascript %}
<script type="text/javascript">
$(document).ready(function(){
    $('.follow-stock').bind('click', function(){
        var stockId = $(this).data("stock_id");
        alert("关注股票" + stockId);
    });

    $('.unfollow-stock').bind('click', function(){
        var stockId = $(this).data("stock_id");
        alert("取消关注股票" + stockId);
    });
});
</script>
{% endblock %}

{% block stock_main%}
<div class="bottom-border bdc-bbb pt-10 pb-5 pl-15">
        <span class="f16 fb">股票一览表</span>
</div>

<ul class="list-inline">
    {% for stock in stocks %}
	<li class="pt-15 col-md-6 col-xs-12 bottom-border bdc-eee">
        <a href="{{stock.get_url}}"><img class="pa avatar-65 avatar-square" alt="{{stock.name}}" src="{{stock.img}}"></a>
        <div class="pl-75 row pr-10">
            <div class="col-md-12 col-xs-12">
                <a class="zx-stocktips" data-stock_id="{{stock.id}}" href="{{stock.get_url}}">{{stock.name}}({{stock.code}})</a>
                <!-- 
                <button class="btn btn-xs btn-primary pull-right mr-10 follow-stock" data-stock_id="{{stock.id}}">添加关注</button>
                <button class="btn btn-xs btn-default pull-right mr-10 unfollow-stock none" data-stock_id="{{stock.id}}">取消关注</button>
                 -->
            </div>
            <div class="col-md-12 col-xs-12 f12 pt-5 pb-15 min-h55">{{stock.des|default:"暂无简介"|str_display:32}}</div>
        </div>
    </li>
    {% endfor %}
</ul>
<div class="blank5"></div>
{{page_params|paging:request}}
{% endblock stock_main%}

www/templates/stock/stock_detail.html
{% extends "stock/base_stock.html" %}
{% load custom_tags %}
{% load custom_filters %}
{% block keywords %}{{stock.name}},{{stock.code}},{{stock.name}}最新消息,{{stock.name}}公告,{{stock.name}}新闻,{{stock.code}}最新消息,{{stock.code}}公告,{{stock.code}}新闻{% endblock keywords %}

{% block description %}{{stock.name}}({{stock.code}})最新动态：上市公司最新消息、公司公告、公司新闻等信息。{% endblock description %}

{% block title %}{{stock.name}}最新消息,{{stock.name}}({{stock.code}})公告新闻汇总{% endblock title %}

{% block css %}
<style type="text/css">
.active>span{
    color: #222;
}
</style>
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{{MEDIA_URL}}js/echarts/echarts.js"></script>
<script type="text/javascript">

require.config({
    paths: {
        echarts: '{{MEDIA_URL}}js/echarts'
    }
});

$(document).ready(function(){
    $('.follow-stock').bind('click', function(){
        var stockId = $(this).data("stock_id");

        $.ZXOperation.followStock(stockId, function(){
            $('.unfollow-stock').show();
            $('.follow-stock').hide();
        });
    });

    $('.unfollow-stock').bind('click', function(){
        var stockId = $(this).data("stock_id");
        
        $.ZXOperation.unfollowStock(stockId, function(){
            $('.unfollow-stock').hide();
            $('.follow-stock').show();
        });
    });

    $('.stock-chart-a').bind('click', function(){
        $('.stock-info-a').removeClass('active');
        $('.stock-info').hide();

        $('.stock-chart-a').removeClass('active').addClass('active');
        $('.stock-chart').show();
    });

    $('.stock-info-a').bind('click', function(){
        $('.stock-chart-a').removeClass('active');
        $('.stock-chart').hide();

        $('.stock-info-a').removeClass('active').addClass('active');
        $('.stock-info').show();
    });
});


var echarts,
    
    calculatePercent = function(length){
        if(length <= 30){
            return 0;
        } else if(30 <= length && length <= 60){
            return 50;
        } else if(60 <= length && length <= 120){
            return 75;
        } else if(120 <= length && length <= 240){
            return 87.5;
        }
    },

    renderKLine = function(xData, yData){
        var kLineChart = echarts.init(document.getElementById('k_line'));

        kLineChart.setOption({
            title: {
                text: '{{stock.name}}({{stock.code}})历史价格'
            },
            grid: {
                x2: 10
            },
            tooltip : {
                trigger: 'axis',
                axisPointer: {
                    type: 'line',
                    lineStyle : {
                      color: '#ddd',
                      width: 1,
                      type: 'solid'
                    }
                },
                formatter: function (params) {
                    var res = params[0].seriesName + ' ' + params[0].name;
                    res += '<br/>  开盘 : ' + params[0].value[0] + '  最高 : ' + params[0].value[3];
                    res += '<br/>  收盘 : ' + params[0].value[1] + '  最低 : ' + params[0].value[2];
                    return res;
                }
            },
            legend: {
                data:['价格'],
                orient: 'horizontal',
                x: 'right',
                padding: [5, 40, 0, 0]
            },
            toolbox: {
                show : true,
                feature : {
                    saveAsImage : {show: true}
                }
            },
            dataZoom : {
                show : true,
                realtime : true,
                start : calculatePercent(xData.length),
                end : 100
            },
            calculable : false,
            xAxis: [{
                type : 'category',
                boundaryGap : true,
                data: xData,
                axisTick: {onGap:false},
                splitLine: {show:false}
            }],
            yAxis: [{
                type: 'value',
                scale: true,
                boundaryGap: [0.01, 0.01]
            }],
            series : [{
                name:'价格',
                type:'k',
                itemStyle: {
                    normal: {
                        color: '#dd2909',
                        color0: '#33aa11',
                        lineStyle: {
                            width: 2,
                            color: '#dd2909',    // 阳线边框颜色
                            color0: '#33aa11'     // 阴线边框颜色
                        }
                    }
                },
                data: yData
            }]
        });
    },

    // 今日个股成交额环比
    renderChain = function(xData, yData){
        var chainChart = echarts.init(document.getElementById('chain'));

        chainChart.setOption({
            title: {
                text: '{{stock.name}}({{stock.code}})历史成交额环比'
            },
            grid: {
                x2: 10
            },
            tooltip : {
                trigger: 'axis',
                axisPointer: {
                    type: 'line',
                    lineStyle : {
                      color: '#ddd',
                      width: 1,
                      type: 'solid'
                    }
                },
                formatter: '<b>{b}</b><br/>{a}: {c} %'
            },
            legend: {
                data:['成交额环比'],
                orient: 'horizontal',
                x: 'right',
                padding: [5, 40, 0, 0]
            },
            toolbox: {
                show : true,
                feature : {
                    saveAsImage : {show: true}
                }
            },
            dataZoom : {
                show : true,
                realtime : true,
                start : calculatePercent(xData.length),
                end : 100
            },
            calculable : false,
            xAxis: [{
                type : 'category',
                boundaryGap : false,
                data: xData,
                splitLine: {show: false}
            }],
            yAxis: [{
                type: 'value',
                axisLabel: {
                    formatter: '{value} %'
                }
            }],
            color: ['#428bca', '#E02C41'],
            series : [{
                name:'成交额环比',
                type:'line',
                smooth: true,
                data: yData
            }]
        });
    },

    renderPercentInTotal = function(xData, yData){
        var percentInTotalChart = echarts.init(document.getElementById('percent_in_total'));

        percentInTotalChart.setOption({
            title: {
                text: '{{stock.name}}({{stock.code}})历史成交额占总额比率'
            },
            grid: {
                x2: 10
            },
            tooltip : {
                trigger: 'axis',
                axisPointer: {
                    type: 'line',
                    lineStyle : {
                      color: '#ddd',
                      width: 1,
                      type: 'solid'
                    }
                },
                formatter: '<b>{b}</b><br/>{a}: {c} ‱'
            },
            legend: {
                data:['成交额占比'],
                orient: 'horizontal',
                x: 'right',
                padding: [5, 40, 0, 0]
            },
            toolbox: {
                show : true,
                feature : {
                    saveAsImage : {show: true}
                }
            },
            dataZoom : {
                show : true,
                realtime : true,
                start : calculatePercent(xData.length),
                end : 100
            },
            calculable : false,
            xAxis: [{
                type : 'category',
                boundaryGap : false,
                data: xData,
                splitLine: {show: false}
            }],
            yAxis: [{
                type: 'value',
                axisLabel: {
                    formatter: '{value} ‱'
                }
            }],
            color: ['#428bca', '#E02C41'],
            series : [{
                name:'成交额占比',
                type:'line',
                smooth: true,
                data: yData
            }]
        });
    },
    
    getStockKLineData = function(){

        ajaxSend(
            "/stock/get_stock_k_line_data", 
            {'stock_id': {{stock.id}} }, 
            function(response){
                if(response.x_data.length <= 0){
                    $.ZXNotice.InfoTopNotice('没有可用的数据');
                    return;
                }

                renderKLine(response.x_data, response.y_data);
            }
        );
    },

    getStockHistoryChainData = function(){

        ajaxSend(
            "/stock/get_stock_history_chain_data", 
            {'stock_id': {{stock.id}} }, 
            function(response){
                if(response.x_data.length <= 0){
                    $.ZXNotice.InfoTopNotice('没有可用的数据');
                    return;
                }

                renderChain(response.x_data, response.y_data);
            }
        );
    },

    getStockHistoryPercentInTotalData = function(){

        ajaxSend(
            "/stock/get_stock_history_percent_in_total_data", 
            {'stock_id': {{stock.id}} }, 
            function(response){
                if(response.x_data.length <= 0){
                    $.ZXNotice.InfoTopNotice('没有可用的数据');
                    return;
                }

                renderPercentInTotal(response.x_data, response.y_data);
            }
        );
    };

require(
    [
        "echarts", 
        "echarts/chart/line", 
        "echarts/chart/bar",
        "echarts/chart/k"
    ],
    function(ec){
        echarts = ec;

        {% if request.user and request.user.can_query_stock_chart %}
        getStockKLineData();
        getStockHistoryChainData();
        getStockHistoryPercentInTotalData();
        {% endif %}
    }
);
</script>
{% endblock %}

{% block stock_main %}
<div class="bottom-border bdc-bbb pl-10 mb-10 mt-5">
    <img class="pa avatar-65 avatar-square" title="{{stock.name}}" alt="{{stock.name}}" src="{{stock.img}}">
    <div class="pl-80 pb-5 pt-5">
        <h4>{{stock.name}}({{stock.code}})</h4>
        <div class="co8 f12 row">
            <div class="{% if request.user and request.user.can_query_stock_chart %} col-md-6 {% else %} col-md-12 {% endif %} ">
                {{stock.feed_count}} 条动态<span class="pl-5 pr-5">•</span>{{stock.following_count}} 人关注
                
                <span class="{% if request.user and request.user.can_query_stock_chart %} a {% else %} pull-right {% endif %}">

                    <button class="btn btn-xs btn-primary ml-10 follow-stock {% if is_follow %}none{% endif %}" data-stock_id="{{stock.id}}">添加关注</button>
                    <button class="btn btn-xs btn-default ml-10 unfollow-stock {% if not is_follow %}none{% endif %}" data-stock_id="{{stock.id}}">取消关注</button>

                </span>
            </div>
            {% if request.user and request.user.can_query_stock_chart %} 
            <div class="col-md-6 text-right">
                <a href="javascript:void(0)" class="active stock-chart-a"><span class="f14 fb">个股图表</span></a>
                <span class="co8 pl-5 pr-5">|</span>
                <a href="javascript:void(0)" class="stock-info-a"><span class="f14 fb">个股资讯</span></a>
            </div>
            {% endif %}
        </div>
    </div>
</div>

<!--图表-->
<div class="stock-chart {% if not request.user or not request.user.can_query_stock_chart %} none {% endif %}">
    <div class="min-h400 mt-15" id="k_line"></div>

    <div class="min-h400 mt-15" id="chain"></div>

    <div class="min-h400 mt-35" id="percent_in_total"></div>
</div>
<!--资讯-->
<div class="stock-info {% if request.user and request.user.can_query_stock_chart %} none {% endif %}">
    <ul class="list-group">
        {% for stock_feed in stock_feeds %}
        <li class="list-group-item no-l-r-bd bdc-eee">
            <div><a href="{{stock_feed.get_url}}" class="f14 black-blue fb">{{stock_feed.question_content|safe}}</a></div>
            <div class="f13 pt-15 line-height-22">{{stock_feed.answer_content|safe}}</div>
            <div class="pt-5 text-right"><span class="co8 f12">{{stock_feed.create_time}}</span></div>
        </li>
        {% endfor %}
    </ul>
    {{page_params|paging:request}}
</div>
{% endblock stock_main %}

{% block stock_right %}
<div class="f16 pb-10 fb pt-15">股票简介</div>
<div>
    <p>{{stock.des|default:"暂无简介"}}</p>
</div>

<div class="f16 pb-10 fb pt-15 mt-15 top-border bdc-eee">主营业务</div>
<div class="line-height-22">{{stock.main_business|default:"暂无"}}</div>

<div class="f16 pb-10 fb pt-15 mt-15 top-border bdc-eee">所属板块</div>
<div class="line-height-22">{{stock.get_belong_board_display}}</div>
{% endblock stock_right %}